sudo: required

language: node_js

node_js:
  - 6

services:
  - docker

before_install:
- docker pull gremlinorm/gremlin-server-neo4j
- ./bin/server

script:
- npm run build; mocha -t 10000 test/index.js test/helpers.js test/vertex.js test/edge.js --exit
