sudo: required

language: node_js

node_js:
  - 6

services:
  - docker

before_install:
- docker pull gremlinorm/gremlin-server-neo4j

script:
- git clone https://github.com/gremlin-orm/gremlin-orm-neo4j.git; cd gremlin-orm-neo4j; docker-compose run --rm --service-ports gremlin-server & sleep 60; cd ..; npm run build; mocha -t 10000 test/index.js test/helpers.js test/vertex.js test/edge.js --exit
